pregdata = {
    7 : "You need to have an ultrasound to determine the location of the pregnancy sac, size and vitality (heartbeat) of the fetus.",
    8 : "You need to have an ultrasound to determine the location of the pregnancy sac, size and vitality (heartbeat) of the fetus.",
    9 : "You need to have an ultrasound to determine the location of the pregnancy sac, size and vitality (heartbeat) of the fetus.",
    10 : "You need to take the following test :Blood count, fasting glucose, urine culture, blood type (and RH antibodies level if negative), rubella antibodies, VDRL, CMV, antibodies, toxoplasma and HBsAG and if necessary an HIV test.",
    11 : "You need to take the following test :Blood count, fasting glucose, urine culture, blood type (and RH antibodies level if negative), rubella antibodies, VDRL, CMV, antibodies, toxoplasma and HBsAG and if necessary an HIV test.",
	12 : "Placental structure (chorionic placenta) and early chromosomal genetic diagnostic testing has to be done.",
	13 : "Placental structure (chorionic placenta) and early chromosomal genetic diagnostic testing has to be done.",
    14 : "You need have an ultrasound, nuchal translucency or fetal development test performed." ,
    15 : "Ultrasound screening exam needs to be done.",
    16 : "Ultrasound screening exam needs to be done.",
    17 : "Triple screen test, fetoprotein or amniocentesis and blood count has to be done.",
    18 : "Triple screen test, fetoprotein or amniocentesis and blood count has to be done.",
    19 : "Triple screen test, fetoprotein or amniocentesis and blood count has to be done.",
    20 : "Triple screen test, fetoprotein or amniocentesis and blood count has to be done.",
    21 : "Triple screen test, fetoprotein or amniocentesis and blood count has to be done.",
    22 : "Late ultrasound anomaly scan has to be done.",
    23 : "Late ultrasound anomaly scan has to be done.",
    24 : "Late ultrasound anomaly scan has to be done.",
    25 : "Late ultrasound anomaly scan has to be done.",
    26 : "You need have glucose tolerance test, blood count and RH antibody levels for those with negative blood type.",
    27 : "You need have glucose tolerance test, blood count and RH antibody levels for those with negative blood type.",
    28 : "You need have a visit to the physician to discuss glucose test results and talk about receiving RH immune globulin if RH negative",
    29 : "You need have a visit to the physician to discuss glucose test results and talk about receiving RH immune globulin if RH negative",
    30 : "You need have a visit to the physician to discuss glucose test results and talk about receiving RH immune globulin if RH negative",
    31 : "Review of fetal growth has to be now!",
    32 : "Review of fetal growth has to be now!",
    33 : "Follow-up visit has to be done.",
    34 : "Weekly tracking of fetal growth weight needs to be done.",
    35 : "Weekly tracking of fetal growth weight needs to be done.",
    36 : "Weekly tracking of fetal growth weight needs to be done.",
    37 : "Weekly tracking of fetal growth weight needs to be done.",
    38 : "Weekly tracking of fetal growth weight needs to be done.",
    39 : "Weekly tracking of fetal growth weight needs to be done.",
    40 : "Follow-up with doctor, ultrasound, monitoring biophysical profile every 2-4 days should be done."
}


babydata = {
	0 : "Baby's dose for BCG vaccine for the prevention of TB and bladder cancer, first dose of HEPB vaccine for the prevention of  Hepatitis B and first dose for POLIOVIRUS vaccine for the prevention of polio is due.",
	1 : "No vaccination is pending.",
	2 : "No vaccination is pending.",
	3 : "No vaccination is pending.",
	4 : "Baby's second dose of HEPB vaccine for the prevention of Hepatitis B and second dose of POLIOVIRUS vaccine for the prevenion of polio is due.",
	5 : "No vaccination is pending.",
	6 : "Baby's first dose of DTP vaccine for the prevention of Dipther ia, Tetanus and  Pertussis, first dose of Hib vaccine for the prevention of infections, first dose of PCV vaccine for the prevention of Pneumonia, first dose of RV vaccine for the prevention of Diarrhea is due.",
	7 : "Baby's first dose of DTP vaccine for the prevention of Dipther ia, Tetanus and  Pertussis, first dose of Hib vaccine for the prevention of infections, first dose of PCV vaccine for the prevention of Pneumonia, first dose of RV vaccine for the prevention of Diarrhea is due.",
	8 : "Baby's third dose of POLIOVIRUS for the prevention of polio is due.",
	9 : "Baby's third dose of POLIOVIRUS for the prevention of polio is due.",
	10 :"Baby's second dose of DTP vaccine for the prevention of Dipther ia, Tetanus and  Pertussis, second dose of Hib vaccine for the prevention of infections, second dose of PCV vaccine for the prevention of Pneumonia, second dose of RV vaccine for the prevention of Diarrhea is due.",
	11 : "Baby's second dose of DTP vaccine for the prevention of Dipther ia, Tetanus and  Pertussis, second dose of Hib vaccine for the prevention of infections, second dose of PCV vaccine for the prevention of Pneumonia, second dose of RV vaccine for the prevention of Diarrhea is due.",
	12 : "Baby's third dose of HEPB vaccine for the prevention of Hepatitis B is due.",
	13 : "Baby's third dose of HEPB vaccine for the prevention of Hepatitis B is due.",
	14 : "Baby's third dose of DTP vaccine for the prevention of Dipther ia, Tetanus and  Pertussis, third dose of Hib vaccine for the prevention of infections, third dose of PCV vaccine for the prevention of Pneumonia, third dose of RV vaccine for the prevention of Diarrhea is due.",
	15 : "Baby's third dose of DTP vaccine for the prevention of Dipther ia, Tetanus and  Pertussis, third dose of Hib vaccine for the prevention of infections, third dose of PCV vaccine for the prevention of Pneumonia, third dose of RV vaccine for the prevention of Diarrhea is due.",
	16 : "Baby's third dose of DTP vaccine for the prevention of Dipther ia, Tetanus and  Pertussis, third dose of Hib vaccine for the prevention of infections, third dose of PCV vaccine for the prevention of Pneumonia, third dose of RV vaccine for the prevention of Diarrhea is due.",
	36 : "Baby's first dose of TYPHOID vaccine for the prevention of Typhoid fever and Diarrhea and first dose of MMR vaccine for the prevention of Mumps and Rubella is due.",
	38 : "Baby's fourth dose of DTP vaccine for the prevention of Dipther ia, Tetanus and  Pertussis, fourth dose of Hib vaccine for the prevention of infections, fourth dose of PCV vaccine for the prevention of Pneumonia is due.",
	52 : "Baby's first dose of Varicella vaccine for the prevention of Chicken pox and HepA vaccine for the prevention of the Liver disease.",
	55 : "Baby's second dose of MMR vaccine for the prevention of Measles, Mumps and Rubella and Varicella vaccine for the prevention of Chicken pox.",
	58 : "Baby's second dose of HepA for the prevention of Liver disease is due.",
	104 : "Baby's second dose of Typhoid vaccine for the prevention of Typhoid Fever and Diarrhea is due.",
	364 : "Baby's Tdap vaccine for the prevention of the Dipther ia, tetanus, and pertuassis is due.",
	468 : "Baby's dose of HPV vaccine for the prevention of cancer and warts is due.",
}
